# Generated by Django 4.1.7 on 2023-03-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
