# Generated by Django 4.1.7 on 2023-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0002_remove_customer_address_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default="<django.db.models.fields.CharField>'s address", max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=255),
        ),
    ]
