# Generated by Django 4.1.7 on 2023-03-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0004_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
