# Generated by Django 4.1.7 on 2023-03-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0008_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
