# Generated by Django 4.1.7 on 2023-03-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0013_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
