# Generated by Django 4.1.7 on 2023-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0014_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
