# Generated by Django 4.1.7 on 2023-03-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0015_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
