# Generated by Django 4.1.7 on 2023-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rest_api', '0016_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
